export const localImages = {
    logo: require("../public/logo/elephant.png"),
    sliderOne: require("../public/slider/slider1.svg"),
    sliderTwo: require("../public/slider/slider2.svg"),
    sliderThree: require("../public/slider/slider3.svg"),
    showcaseOne: require("../public/showcase/project1.webp"),
    showcaseTwo: require("../public/showcase/project2.jpeg"),
    showcaseThree: require("../public/showcase/project3.jpeg"),
    teamOne: require("../public/team/team1.png"),
    teamTwo: require("../public/team/team2.jpeg"),
    teamThree: require("../public/team/team3.jpg"),
    teamFour: require("../public/team/team4.jpg"),
    contactUs: require("../public/contact/contact.svg"),
    visionOne: require("../public/vision/vision1.jpeg"),
    visionTwo: require("../public/vision/vision2.jpg"),
};